# weighLoading - вес, который прямо сейчас несет игрок

# Устанавливаем значение в 0
    scoreboard players set @s weighLoading 0

# Рассчитываем, что мы несем
    #Оружие
        scoreboard players add @s[hasitem={item=arx:costorub}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:cult_warrior_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:delimiter}] weighLoading 10
        scoreboard players add @s[hasitem={item=arx:golden_longsword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:dorionite_dismantler}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:steel_heavy_crusher}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:steel_light_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:blood_waiting}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:tearing_flesh}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:bone_dagger}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:spear_with_gold_inlays}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:steel_wide_shortsword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:steel_wide_shortsword_with_special_guard}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:golden_ossified_dagger}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:powered_steel_wide_shortsword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:golden_dagger_fang}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:hunting_cast_iron_knife}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:steel_sharp_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:simple_iron_dagger}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:dagger_fang}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:longed_cast_iron_dagger}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:notched_durasteel_dagger}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:simple_stone_dagger}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:fish_knife}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:podlik}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:chloronite_dagger}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:steel_advanced_guard_dagger}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:dagger_of_the_gap}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:dagger_with_golden_blade}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:vicious_dagger}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:vicious_dagger_refined}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:even}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:cast_iron_hammer_crusher}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:flesh_sword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:dorionite_hammer}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:heavy_axe_with_chloronite_inlays}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:petrified_sword}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:rose_crusher}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:bronze_fang}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:wooden_heavy_crusher}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:altaite_small_hammer}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:bronze_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:copper_heavy_battleaxe}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:dorionite_battleaxe}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:dorionite_powered_battleaxe}] weighLoading 8
        scoreboard players add @s[hasitem={item=arx:wooden_wide_sword}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:red_crystal_crusher}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:plumbum_small_hammer}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_chorper}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:durasteel_sword_with_bronze_inlays}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:wooden_heavy_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:altaite_battlehammer}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:ideal_altaite_sword}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:durasteel_longsword}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:dorionite_secyra_with_sapphiers}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:netherite_crusher}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:netherite_heavy_secyra}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:leave_axe}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:stone_heavy_crusher}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:riolik_hammer}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:cast_iron_board}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:duraluminium_crusher}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:caryite_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:bronze_crusher}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:full_golden_longsword}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:durasteel_ripper}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:dorionite_small_battleaxe}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:bronze_great_battleaxe}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:caryite_small_battleaxe}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:stone_tomahawk}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:iron_default_axe}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:wooden_very_heavy_crusher}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:naginitis_battleaxe}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:elder_crusher}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:caryite_and_toliriite_sword}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:naginits_and_forfacorite_sword}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:netherite_secyra}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:riolik_heavy_sword}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:duraluminium_short_sword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:cast_iron_hammer}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:netherite_bonecrusher}] weighLoading 9
        scoreboard players add @s[hasitem={item=arx:cast_netherite_crusher}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:steel_heavy_sword}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:dorionite_ripper}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:toliriite_ripper}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:red_crystal_heavy_sword}] weighLoading 8
        scoreboard players add @s[hasitem={item=arx:toliriite_cutter}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:bronze_crusher_with_cornelian}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:lamenite_megahammer}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:netherite_blade}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:bronze_and_caryite_axe}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:clear_dorionite_sword}] weighLoading 8
        scoreboard players add @s[hasitem={item=arx:duraluminium_sword_with_draphorite_inlays}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:dorionite_megahammer}] weighLoading 10
        scoreboard players add @s[hasitem={item=arx:caryite_and_toliriite_wide_sword}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:durasteel_extreme_long_sword}] weighLoading 13
        scoreboard players add @s[hasitem={item=arx:bronze_hammer}] weighLoading 9
        scoreboard players add @s[hasitem={item=arx:draphorite_sword}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:duraluminium_dismantler_with_draphorite_inlays}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:cast_iron_heavy_crusher}] weighLoading 9
        scoreboard players add @s[hasitem={item=arx:cast_iron_battleaxe_with_chloronite_inlays}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:durasteel_wide_greatsword}] weighLoading 15
        scoreboard players add @s[hasitem={item=arx:wide_cross_sword}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:harbinger_of_dawn}] weighLoading 8
        scoreboard players add @s[hasitem={item=arx:caryite_delimiter}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:caryite_sword_with_sapphire}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:bronze_and_gold_alloy_battleaxe}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:steel_big_longsword}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:ravensword}] weighLoading 8
        scoreboard players add @s[hasitem={item=arx:steel_longsword_with_altaite_inlays}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:clear_caryite_crusher}] weighLoading 8
        scoreboard players add @s[hasitem={item=arx:flesh_hell_sword}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:dorionite_long_sword}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:cast_iron_greatsword}] weighLoading 13
        scoreboard players add @s[hasitem={item=arx:elder_battleboard}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:tin_heavy_sword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:elder_white_crusher}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:chloronite_big_sword}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:duraluminium_delimiter}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:cast_iron_alebard}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_lance}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:cast_iron_lance}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:duraluminium_lance}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:durasteel_lance}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:durasteel_spear}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:netherite_lance}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:steel_spear}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:netherite_naginata}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:durasteel_lance_with_draphorite_inlays}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:dorionite_lance}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:durasteel_and_aluminium_lance}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:bronze_lance}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:cast_iron_longsword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:naginitis_longsword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:simple_iron_longsword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:sacrificial_iron_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:plumbum_full_small_hammer}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:wooden_longsword}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:plumbum_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:netherite_ripper}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:caryite_saber}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:duraluminium_battleaxe_with_draphorite_inlays}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_simple_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:copper_sword_hook}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:simple_iron_axe}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:wooden_simple_sword}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:steel_saber}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:durasteel_simple_longsword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:dorionite_battleaxe_with_caryite_inlays}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:dorionite_double_edged_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:plumbum_longsword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:aluminium_sword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:simple_iron_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:iron_wide_sword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_weighted_sword}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:aluminium_curved_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:iron_wide_heavy_sword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:bronze_longed_sword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_sword_with_copper_guard}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:bronze_longsword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:bronze_heighted_battleaxe}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:steel_mace}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:plumbum_axe}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_longsword_with_copper_guard}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_longsword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:tin_curved_saber}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:steel_crossword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:bronze_trident}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:durasteel_streight_longsword}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:tin_small_battleaxe}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:plumbum_small_longsword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:wooden_one_sided_sword}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:steel_sword_with_golden_guard}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:wooden_battleaxe}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:plumbum_heighted_longsword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:naginitis_weighted_battleaxe}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:altaite_saber}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:cast_iron_long_saber}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:durasteel_small_longsword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:golden_trident}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:forfacorite_longsword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:stone_longsword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:steel_battleaxe}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:plumbum_lighted_small_longsword}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:duraluminium_great_battleaxe}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:scythe_altaite}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:scythe_netherite}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:scythe_caryite}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:scythe_tin}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:scythe_chloronite}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:scythe_toliriite}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:scythe_steel}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:scythe_lamenite}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:scythe_naginitis}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:jagged_lance}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_alebard}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:vicious_lance}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:vicious_lance_refined}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:durasteel_sword_with_dorionite}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_heavy_longsword}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:steel_tooth}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:plumbum_dark_sword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:plumbum_simple_sword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_classic_sword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_sword_with_red_guard}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:powered_steel_shortsword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_shortsword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:steel_dark_shortsword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:chloronite_shortsword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:caryite_heavysword}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:cast_iron_tooth}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:steel_sword_with_gold_inlay}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:holy_sword}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:aluminium_simple_sword}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:steel_simple_blade}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:steel_cleaver}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:plumbum_saber}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:wooden_carved_sword}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:long_steel_sword_with_draphorite_inlays}] weighLoading 4

        scoreboard players add @s[hasitem={item=arx:staff_san}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_caryite}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_wooden}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_dragon}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_gold}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_netherite_with_ruby}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_dark_netherite}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_golden_with_sapphire}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_chrysolite}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_naginitis}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_cast_iron_with_chrysolite}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_of_phoenix}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_with_ruby}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_with_skull}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_of_forest}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_of_twilight}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_golden_with_chrysolite}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_simple_with_ruby}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_chloronite}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_wooden_with_chrysolite}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_dorionite_with_caryite}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_with_beryl}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_wooden_with_olivine}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_tin_with_gold}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_dorionite}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_steel_with_topaz}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_kon}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_golden_with_violet_handle}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_of_scarlet_moon}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_battle}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:staff_of_hell}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_of_snowlands}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_din}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_sin}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_of_shaman}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_precious}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_of_angel}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_golden_cross}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_fulminant}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:staff_of_heaven}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:vicious_staff}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:vicious_staff_refined}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:sturdy_staff}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:golden_moon_radiance}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:master_of_fates}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:composite_toothed_sawsword}] weighLoading 5

    #Особые предметы
        scoreboard players add @s[hasitem={item=arx:shackles}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:heater}] weighLoading 3

    #Одежда
        scoreboard players add @s[hasitem={item=arx:apprentice_robe}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:archmage_robe}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:big_hat}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:big_hat_dyed_blue}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:big_hat_dyed_red}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:big_hat_dyed_white}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:big_hat_dyed_black}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:black_jacket}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:bloody_robe}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:blue_pirate_hat}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:bone_mask}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:cape_of_purple_dust}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:cheap_cape}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:citizen_clothes}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:clothes_of_roaring_winds}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:dealer_clothes}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:demon_mask}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:derek_hat}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:diadem_of_desert_wanderer}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:dress_of_green_rose}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:elven_tunic}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:exquisite_town_clothes}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:farmers_clothes}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:fox_mask}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:fox_sakura_mask}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:gown_of_desert_wanderer}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:gray_dress}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:night_hunter_dress}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:horn_mask}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:hu_tao_hat}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:morning_forest_clothes}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:night_vision_device}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:pirate_clothes}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:pirate_hat}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:plague_doctor_mask}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:purple_cape}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:ranger_clothes}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:red_cape}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:red_hat}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:rich_jacket}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:robe_of_clouds}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:robe_of_desert}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:sailors_clothing}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:scarlet_dress}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:scientists_clothes}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:shepherd_clothes}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:simple_open_clothing}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:simple_skin_clothes}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:simple_worker_clothes}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:slave_clothes}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:steampunk_pants}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:stroller_clothes}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:traveler_cape}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:wanderer_jacket}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:watermelon_hat}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:white_hat}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:wide_hat}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:women_face}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:youkai_mask}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:descriptor}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:pink_dress}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:home_gown}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:blue_dawn_dress}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:archer_coat}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:astronomer_cape}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:dark_captain_jacket}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:dark_shepherd_clothes}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:desert_traders_hood}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:desert_traders_clothes}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:eclipse_tunic}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:elite_gown}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:forest_fairy_bandages}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:mantle_of_swamp_alchemist}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:mayor_coat}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:moon_fierce}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:red_dress}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:red_sunset_dress}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:robe_of_dark_priest}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:royal_gown}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:scarlet_cape}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:swordsman_clothes}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:twilight_cape}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:twilight_dress}] weighLoading 1

    # Религиозная одежда
        scoreboard players add @s[hasitem={item=arx:pallas_apprentice_robe}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:pires_apprentice_robe}] weighLoading 1
        scoreboard players add @s[hasitem={item=arx:necro_mantle}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:pallas_mage_mantle}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:pires_mage_mantle}] weighLoading 2

    #Лёгкая броня
        scoreboard players add @s[hasitem={item=arx:armored_blue_clothes}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:armored_chain_mail_armor}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:armored_robe}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:beryl_armor}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:crown_with_ruby}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:dwarf_armor}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:dwarf_helmet}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:golden_crown}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:golden_silk_coat}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:knight_chain_mail}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:knight_chain_mail_helmet}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:knight_light_armor}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:knight_light_helmet}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:light_chestplate}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:lightweight_combat_armor}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:militiaman_armor}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:militiaman_helmet}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:moon_mask}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:night_knight}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:night_knight_helmet}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:precious_coat}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:protector_armor}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:raven_armor}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:silk_reinforced_armor}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:skull_mask}] weighLoading 2
        scoreboard players add @s[hasitem={item=arx:warrior_chain_mail}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:warrior_helmet}] weighLoading 3

        scoreboard players add @s[hasitem={item=arx:pallas_assasin_clothing}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:pires_ranger_coat}] weighLoading 3

        scoreboard players add @s[hasitem={item=arx:baron_gambeson}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:desert_protector_armor}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:hell_fighter_armor}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:swordsman_armor}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:light_leather_armor}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:snow_lord_armor}] weighLoading 5

    #Тяжёлая броня
        scoreboard players add @s[hasitem={item=arx:crimson_armor}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:dark_knight_armor}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:dark_knight_helmet}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:dragon_slayer_armor}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:dragon_slayer_helmet}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:duke_armor}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:duke_helmet}] weighLoading 3
        scoreboard players add @s[hasitem={item=arx:durasteel_armor}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:durasteel_helmet}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:heavy_plate_armor}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:heavy_plate_helmet}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:knight_armor}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:knight_helmet}] weighLoading 4
        scoreboard players add @s[hasitem={item=arx:knight_steel_armor}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:northerner_armor}] weighLoading 7
        scoreboard players add @s[hasitem={item=arx:northerner_helmet}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:old_camp_armor}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:precursor_armor}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:precursor_helmet}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:purple_plate_helmet}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:purple_plates}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:steeletherite_armor}] weighLoading 8
        scoreboard players add @s[hasitem={item=arx:lamenite_plate_armor}] weighLoading 8

        scoreboard players add @s[hasitem={item=arx:silver_samurai_helmet}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:silver_samurai_armor}] weighLoading 8
        scoreboard players add @s[hasitem={item=arx:plate_chainmail_armor}] weighLoading 6
        scoreboard players add @s[hasitem={item=arx:snow_warrior_armor}] weighLoading 7

        scoreboard players add @s[hasitem={item=arx:pires_paladin_armor}] weighLoading 5
        scoreboard players add @s[hasitem={item=arx:pallas_conqueror_armor}] weighLoading 7